name: Daily Webhook Test

on:
  schedule:
    # UTC 03:00 (한국 시간 12:00)에 실행 설정
    # GitHub 서버 부하에 따라 12:10 ~ 12:30 사이쯤 메시지가 올 수 있습니다.
    - cron: '0 3 * * *'
  workflow_dispatch: # 수동 실행 버튼 유지

jobs:
  send_webhook:
    runs-on: ubuntu-latest
    steps:
      - name: Send POST Request
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d '{"text":"[GitHub Actions] 정기 스케줄 알림 테스트입니다. (설정시간 UTC 03:00)"}' \
          "https://kakaowork.com/bots/hook/55818b68831347139dbb65199eee3031"
