name: Send Tuesday Webhook
on:
  workflow_dispatch: # Actions íƒ­ì—ì„œ 'Run workflow' ë²„íŠ¼ìœ¼ë¡œ ì¦‰ì‹œ í…ŒìŠ¤íŠ¸ ê°€ëŠ¥
  schedule:
    - cron: '30 0 * * 2' # ë§¤ì£¼ í™”ìš”ì¼ ì˜¤ì „ 9ì‹œ 30ë¶„ (í•œêµ­ ì‹œê°„)

jobs:
  send_webhook:
    runs-on: ubuntu-latest
    steps:
      - name: Send KakaoWork Message
        run: |
          curl -X POST "https://kakaowork.com/bots/hook/55818b68831347139dbb65199eee3031" \
          -H "Content-Type: application/json" \
          -d @- <<EOF
          {
            "text": "í™”ìš”ì¼ ì˜¤ì „ 10ì‹œ ì•Œë¦¼",
            "blocks": [
              {
                "type": "header",
                "text": "ğŸ“¢ ì£¼ê°„íšŒì˜ë¡ í•˜ë‹¨ ì´ìŠˆ ê°±ì‹  ì‹œê°„",
                "style": "blue"
              },
              {
                "type": "text",
                "text": "í™”ìš”ì¼ ì˜¤ì „ 10ì‹œ ì…ë‹ˆë‹¤~",
                "markdown": true
              },
              {
                "type": "button",
                "text": "ë°”ë¡œê°€ê¸°",
                "style": "primary",
                "action": {
                  "type": "open_system_browser",
                  "value": "https://docs.google.com/spreadsheets/d/1iCDME2uagyXeRY9KiWOOxycE1i4gxHwGCRigYCdvmus/edit?usp=sharing"
                }
              }
            ]
          }
          EOF
